on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22

    name: Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile # pnpm 11 change to `pnpm ci`
      - run: pnpm run lint
      - run: pnpm run build
